repos:
  - repo: local
    hooks:
      - id: run-unit-test
        name: run unit tests
        entry: /Users/leo/Desktop/learn/django/quotation_system/venv/bin/python -m pytest -m unit
        language: system
        pass_filenames: false